version: 2

workflows:
  version: 2
  test:
    jobs:
      - python_3.9
      - python_3.10
      - python_3.11
      - python_3.12
      - python_3.13
      

template: &template
  docker:
    - image: ubuntu:noble
  steps:
    - checkout
    - run:
        name: Set up git + miniconda
        command: |
          apt update
          apt upgrade -y
          DEBIAN_FRONTEND=noninteractive apt install -y wget git-all curl
          cd $HOME
    - run:
        name: Set up environment, dependencies and run tests
        command: |
          export PATH="$HOME/.pixi/bin:$PATH"
          pip install -e ".[dev]"
          pytest src/test --disable-pytest-warnings

jobs:
  python_3.9:
    <<: *template
    environment:
      PYTHON_VERSION: "3.9"
  python_3.10:
    <<: *template
    environment:
      PYTHON_VERSION: "3.10"
  python_3.11:
    <<: *template
    environment:
      PYTHON_VERSION: "3.11"
  python_3.12:
    <<: *template
    environment:
      PYTHON_VERSION: "3.12"
  python_3.13:
    <<: *template
    environment:
      PYTHON_VERSION: "3.13"
